language: csharp
solution: ./src/src_net/MonoClient.sln
node_js:
  - "7"
mono: latest
dotnet: 2.1.301
install:
  - npm install
  - npm run build_prod
  - npm run tests
script:
  - dotnet build ./src/src_net/MonoClient
  - dotnet restore ./src/src_net
  - msbuild /p:Configuration=Debug ./src/src_net/MonoClient.sln
